apiVersion: valhalla.pandaritrl/v1alpha1
kind: Valhalla
metadata:
  name: example
spec:
  pbfUrl: https://download.geofabrik.de/australia-oceania/marshall-islands-latest.osm.pbf
  image: pandaritrl/valhalla-worker:latest
  builderImage: pandaritrl/valhalla-builder:latest
  minReplicas: 2
  maxReplicas: 5
  resources:
    requests:
      cpu: "1000m"
      memory: "100Mi"
    limits:
      cpu: "1500m"
      memory: "150Mi"
  persistence:
    storage: "100Mi"
    storageClassName: standard-rwx
    accessMode: ReadWriteMany
  service:
    type: LoadBalancer
    annotations:
      example-annotation: "example-annotation"
  predictedTraffic:
    url: https://example.com
    schedule: "*/3 * * * *"
